title: 'hackintoanetwork.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
# baseurl: "/jekyll-theme-console-demo-light"
url: "https://hackintoanetwork.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: hacker

footer: 'follow me on <a href="https://github.com/hackintoanetwork">Github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
